In [25]:
from scipy import stats
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
df = pd.read_csv('datanorita.csv')
df

    berat badan  tinggi badan  tekanan darah  lingkar perut
0            80           163            106             61
1            51           180            117             40
2            43           150            106             61
3            65           156            105             58
4            48           150            113             40
5            76           155            113             58
6            45           158            126             62
7            54           158            129             63
8            65           153            106             58
9            66           153            104             45
10           73           169            114             57
11           53           151            119             62
12           74           167            110             53
13           48           173            118             46
14           68           179            124             48
15           41           163            104             70
16           54           163            128             55
17           45           155            112             42
18           71           154            116             60
19           72           162            110             60
20           62           167            122             58
21           73           168            116             69
22           45           158            100             66
23           48           151            116             61
24           63           172            106             62
25           61           175            110             57
26           76           166            102             70
27           77           153            129             41
28           73           164            128             50
29           51           159            123             67
..          ...           ...            ...            ...
70           68           175            123             47
71           53           166            113             42
72           58           174            107             56
73           67           175            121             40
74           76           153            121             56
75           57           159            128             44
76           55           154            127             62
77           51           150            129             51
78           66           160            120             60
79           44           161            128             56
80           47           178            119             66
81           60           159            110             47
82           76           166            117             57
83           58           171            123             67
84           56           151            108             46
85           50           165            130             46
86           67           158            104             53
87           63           158            111             68
88           66           157            127             58
89           43           151            117             51
90           61           173            128             48
91           42           172            124             64
92           53           152            104             51
93           46           161            112             42
94           76           164            115             41
95           79           160            114             63
96           73           159            107             41
97           42           153            127             59
98           44           161            127             63
99           54           163            124             68

[100 rows x 4 columns]

In [27]:
from IPython.display import HTML, display
import tabulate
table=[
        ["method"]+[x for x in df.columns],
        ["count()"]+[df[col].count() for col in df.columns],
        ["mean()"]+[df[col].mean() for col in df.columns],
        ["std()"]+["{:.2f}".format(df[col].std()) for col in df.columns],
        ["min()"]+[df[col].min() for col in df.columns],
        ["max()"]+[df[col].max() for col in df.columns],
        ["q1()"]+[df[col].quantile(0.25) for col in df.columns],
        ["q2()"]+[df[col].quantile(0.50) for col in df.columns],
        ["q3"]+[df[col].quantile(0.75) for col in df.columns],
        ["skew"]+["{:.2f}".format(df[col].skew()) for col in df.columns],
     ]

display(HTML(tabulate.tabulate(table, tablefmt='html')))